/*
Tabular API

Tabular OpenAPI Definition

API version: 1.54.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tabular

import (
	"encoding/json"
)

// checks if the GetRoleDatabaseGrantsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRoleDatabaseGrantsResponse{}

// GetRoleDatabaseGrantsResponse struct for GetRoleDatabaseGrantsResponse
type GetRoleDatabaseGrantsResponse struct {
	Authorizations []DatabaseAuthorization `json:"authorizations,omitempty"`
}

// NewGetRoleDatabaseGrantsResponse instantiates a new GetRoleDatabaseGrantsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRoleDatabaseGrantsResponse() *GetRoleDatabaseGrantsResponse {
	this := GetRoleDatabaseGrantsResponse{}
	return &this
}

// NewGetRoleDatabaseGrantsResponseWithDefaults instantiates a new GetRoleDatabaseGrantsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRoleDatabaseGrantsResponseWithDefaults() *GetRoleDatabaseGrantsResponse {
	this := GetRoleDatabaseGrantsResponse{}
	return &this
}

// GetAuthorizations returns the Authorizations field value if set, zero value otherwise.
func (o *GetRoleDatabaseGrantsResponse) GetAuthorizations() []DatabaseAuthorization {
	if o == nil || IsNil(o.Authorizations) {
		var ret []DatabaseAuthorization
		return ret
	}
	return o.Authorizations
}

// GetAuthorizationsOk returns a tuple with the Authorizations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRoleDatabaseGrantsResponse) GetAuthorizationsOk() ([]DatabaseAuthorization, bool) {
	if o == nil || IsNil(o.Authorizations) {
		return nil, false
	}
	return o.Authorizations, true
}

// HasAuthorizations returns a boolean if a field has been set.
func (o *GetRoleDatabaseGrantsResponse) HasAuthorizations() bool {
	if o != nil && !IsNil(o.Authorizations) {
		return true
	}

	return false
}

// SetAuthorizations gets a reference to the given []DatabaseAuthorization and assigns it to the Authorizations field.
func (o *GetRoleDatabaseGrantsResponse) SetAuthorizations(v []DatabaseAuthorization) {
	o.Authorizations = v
}

func (o GetRoleDatabaseGrantsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRoleDatabaseGrantsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Authorizations) {
		toSerialize["authorizations"] = o.Authorizations
	}
	return toSerialize, nil
}

type NullableGetRoleDatabaseGrantsResponse struct {
	value *GetRoleDatabaseGrantsResponse
	isSet bool
}

func (v NullableGetRoleDatabaseGrantsResponse) Get() *GetRoleDatabaseGrantsResponse {
	return v.value
}

func (v *NullableGetRoleDatabaseGrantsResponse) Set(val *GetRoleDatabaseGrantsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRoleDatabaseGrantsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRoleDatabaseGrantsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRoleDatabaseGrantsResponse(val *GetRoleDatabaseGrantsResponse) *NullableGetRoleDatabaseGrantsResponse {
	return &NullableGetRoleDatabaseGrantsResponse{value: val, isSet: true}
}

func (v NullableGetRoleDatabaseGrantsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRoleDatabaseGrantsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
