/*
Tabular API

Tabular OpenAPI Definition

API version: 1.56.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tabular

import (
	"encoding/json"
)

// checks if the UpdateLabelFieldMaskingRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateLabelFieldMaskingRequest{}

// UpdateLabelFieldMaskingRequest struct for UpdateLabelFieldMaskingRequest
type UpdateLabelFieldMaskingRequest struct {
	MaskMode *string `json:"maskMode,omitempty"`
}

// NewUpdateLabelFieldMaskingRequest instantiates a new UpdateLabelFieldMaskingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateLabelFieldMaskingRequest() *UpdateLabelFieldMaskingRequest {
	this := UpdateLabelFieldMaskingRequest{}
	return &this
}

// NewUpdateLabelFieldMaskingRequestWithDefaults instantiates a new UpdateLabelFieldMaskingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateLabelFieldMaskingRequestWithDefaults() *UpdateLabelFieldMaskingRequest {
	this := UpdateLabelFieldMaskingRequest{}
	return &this
}

// GetMaskMode returns the MaskMode field value if set, zero value otherwise.
func (o *UpdateLabelFieldMaskingRequest) GetMaskMode() string {
	if o == nil || IsNil(o.MaskMode) {
		var ret string
		return ret
	}
	return *o.MaskMode
}

// GetMaskModeOk returns a tuple with the MaskMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLabelFieldMaskingRequest) GetMaskModeOk() (*string, bool) {
	if o == nil || IsNil(o.MaskMode) {
		return nil, false
	}
	return o.MaskMode, true
}

// HasMaskMode returns a boolean if a field has been set.
func (o *UpdateLabelFieldMaskingRequest) HasMaskMode() bool {
	if o != nil && !IsNil(o.MaskMode) {
		return true
	}

	return false
}

// SetMaskMode gets a reference to the given string and assigns it to the MaskMode field.
func (o *UpdateLabelFieldMaskingRequest) SetMaskMode(v string) {
	o.MaskMode = &v
}

func (o UpdateLabelFieldMaskingRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateLabelFieldMaskingRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaskMode) {
		toSerialize["maskMode"] = o.MaskMode
	}
	return toSerialize, nil
}

type NullableUpdateLabelFieldMaskingRequest struct {
	value *UpdateLabelFieldMaskingRequest
	isSet bool
}

func (v NullableUpdateLabelFieldMaskingRequest) Get() *UpdateLabelFieldMaskingRequest {
	return v.value
}

func (v *NullableUpdateLabelFieldMaskingRequest) Set(val *UpdateLabelFieldMaskingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateLabelFieldMaskingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateLabelFieldMaskingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateLabelFieldMaskingRequest(val *UpdateLabelFieldMaskingRequest) *NullableUpdateLabelFieldMaskingRequest {
	return &NullableUpdateLabelFieldMaskingRequest{value: val, isSet: true}
}

func (v NullableUpdateLabelFieldMaskingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateLabelFieldMaskingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
