/*
Tabular API

Tabular OpenAPI Definition

API version: 1.56.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tabular

import (
	"encoding/json"
)

// checks if the CreateLabelRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLabelRequest{}

// CreateLabelRequest struct for CreateLabelRequest
type CreateLabelRequest struct {
	LabelName            *string  `json:"labelName,omitempty"`
	Description          *string  `json:"description,omitempty"`
	AllowedResourceTypes []string `json:"allowedResourceTypes,omitempty"`
}

// NewCreateLabelRequest instantiates a new CreateLabelRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLabelRequest() *CreateLabelRequest {
	this := CreateLabelRequest{}
	return &this
}

// NewCreateLabelRequestWithDefaults instantiates a new CreateLabelRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLabelRequestWithDefaults() *CreateLabelRequest {
	this := CreateLabelRequest{}
	return &this
}

// GetLabelName returns the LabelName field value if set, zero value otherwise.
func (o *CreateLabelRequest) GetLabelName() string {
	if o == nil || IsNil(o.LabelName) {
		var ret string
		return ret
	}
	return *o.LabelName
}

// GetLabelNameOk returns a tuple with the LabelName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLabelRequest) GetLabelNameOk() (*string, bool) {
	if o == nil || IsNil(o.LabelName) {
		return nil, false
	}
	return o.LabelName, true
}

// HasLabelName returns a boolean if a field has been set.
func (o *CreateLabelRequest) HasLabelName() bool {
	if o != nil && !IsNil(o.LabelName) {
		return true
	}

	return false
}

// SetLabelName gets a reference to the given string and assigns it to the LabelName field.
func (o *CreateLabelRequest) SetLabelName(v string) {
	o.LabelName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateLabelRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLabelRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateLabelRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateLabelRequest) SetDescription(v string) {
	o.Description = &v
}

// GetAllowedResourceTypes returns the AllowedResourceTypes field value if set, zero value otherwise.
func (o *CreateLabelRequest) GetAllowedResourceTypes() []string {
	if o == nil || IsNil(o.AllowedResourceTypes) {
		var ret []string
		return ret
	}
	return o.AllowedResourceTypes
}

// GetAllowedResourceTypesOk returns a tuple with the AllowedResourceTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLabelRequest) GetAllowedResourceTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedResourceTypes) {
		return nil, false
	}
	return o.AllowedResourceTypes, true
}

// HasAllowedResourceTypes returns a boolean if a field has been set.
func (o *CreateLabelRequest) HasAllowedResourceTypes() bool {
	if o != nil && !IsNil(o.AllowedResourceTypes) {
		return true
	}

	return false
}

// SetAllowedResourceTypes gets a reference to the given []string and assigns it to the AllowedResourceTypes field.
func (o *CreateLabelRequest) SetAllowedResourceTypes(v []string) {
	o.AllowedResourceTypes = v
}

func (o CreateLabelRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLabelRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LabelName) {
		toSerialize["labelName"] = o.LabelName
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.AllowedResourceTypes) {
		toSerialize["allowedResourceTypes"] = o.AllowedResourceTypes
	}
	return toSerialize, nil
}

type NullableCreateLabelRequest struct {
	value *CreateLabelRequest
	isSet bool
}

func (v NullableCreateLabelRequest) Get() *CreateLabelRequest {
	return v.value
}

func (v *NullableCreateLabelRequest) Set(val *CreateLabelRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLabelRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLabelRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLabelRequest(val *CreateLabelRequest) *NullableCreateLabelRequest {
	return &NullableCreateLabelRequest{value: val, isSet: true}
}

func (v NullableCreateLabelRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLabelRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
