/*
Tabular API

Tabular OpenAPI Definition

API version: 1.56.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tabular

import (
	"encoding/json"
)

// checks if the ListRoleLabelGrantsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListRoleLabelGrantsResponse{}

// ListRoleLabelGrantsResponse struct for ListRoleLabelGrantsResponse
type ListRoleLabelGrantsResponse struct {
	Grants []RoleGrantDetail `json:"grants,omitempty"`
}

// NewListRoleLabelGrantsResponse instantiates a new ListRoleLabelGrantsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListRoleLabelGrantsResponse() *ListRoleLabelGrantsResponse {
	this := ListRoleLabelGrantsResponse{}
	return &this
}

// NewListRoleLabelGrantsResponseWithDefaults instantiates a new ListRoleLabelGrantsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListRoleLabelGrantsResponseWithDefaults() *ListRoleLabelGrantsResponse {
	this := ListRoleLabelGrantsResponse{}
	return &this
}

// GetGrants returns the Grants field value if set, zero value otherwise.
func (o *ListRoleLabelGrantsResponse) GetGrants() []RoleGrantDetail {
	if o == nil || IsNil(o.Grants) {
		var ret []RoleGrantDetail
		return ret
	}
	return o.Grants
}

// GetGrantsOk returns a tuple with the Grants field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListRoleLabelGrantsResponse) GetGrantsOk() ([]RoleGrantDetail, bool) {
	if o == nil || IsNil(o.Grants) {
		return nil, false
	}
	return o.Grants, true
}

// HasGrants returns a boolean if a field has been set.
func (o *ListRoleLabelGrantsResponse) HasGrants() bool {
	if o != nil && !IsNil(o.Grants) {
		return true
	}

	return false
}

// SetGrants gets a reference to the given []RoleGrantDetail and assigns it to the Grants field.
func (o *ListRoleLabelGrantsResponse) SetGrants(v []RoleGrantDetail) {
	o.Grants = v
}

func (o ListRoleLabelGrantsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListRoleLabelGrantsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Grants) {
		toSerialize["grants"] = o.Grants
	}
	return toSerialize, nil
}

type NullableListRoleLabelGrantsResponse struct {
	value *ListRoleLabelGrantsResponse
	isSet bool
}

func (v NullableListRoleLabelGrantsResponse) Get() *ListRoleLabelGrantsResponse {
	return v.value
}

func (v *NullableListRoleLabelGrantsResponse) Set(val *ListRoleLabelGrantsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListRoleLabelGrantsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListRoleLabelGrantsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListRoleLabelGrantsResponse(val *ListRoleLabelGrantsResponse) *NullableListRoleLabelGrantsResponse {
	return &NullableListRoleLabelGrantsResponse{value: val, isSet: true}
}

func (v NullableListRoleLabelGrantsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListRoleLabelGrantsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
