/*
Tabular API

Tabular OpenAPI Definition

API version: 1.54.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tabular

import (
	"encoding/json"
)

// checks if the ListTableRoleGrantsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListTableRoleGrantsResponse{}

// ListTableRoleGrantsResponse struct for ListTableRoleGrantsResponse
type ListTableRoleGrantsResponse struct {
	Grants []RoleGrantDetail `json:"grants,omitempty"`
}

// NewListTableRoleGrantsResponse instantiates a new ListTableRoleGrantsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTableRoleGrantsResponse() *ListTableRoleGrantsResponse {
	this := ListTableRoleGrantsResponse{}
	return &this
}

// NewListTableRoleGrantsResponseWithDefaults instantiates a new ListTableRoleGrantsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTableRoleGrantsResponseWithDefaults() *ListTableRoleGrantsResponse {
	this := ListTableRoleGrantsResponse{}
	return &this
}

// GetGrants returns the Grants field value if set, zero value otherwise.
func (o *ListTableRoleGrantsResponse) GetGrants() []RoleGrantDetail {
	if o == nil || IsNil(o.Grants) {
		var ret []RoleGrantDetail
		return ret
	}
	return o.Grants
}

// GetGrantsOk returns a tuple with the Grants field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListTableRoleGrantsResponse) GetGrantsOk() ([]RoleGrantDetail, bool) {
	if o == nil || IsNil(o.Grants) {
		return nil, false
	}
	return o.Grants, true
}

// HasGrants returns a boolean if a field has been set.
func (o *ListTableRoleGrantsResponse) HasGrants() bool {
	if o != nil && !IsNil(o.Grants) {
		return true
	}

	return false
}

// SetGrants gets a reference to the given []RoleGrantDetail and assigns it to the Grants field.
func (o *ListTableRoleGrantsResponse) SetGrants(v []RoleGrantDetail) {
	o.Grants = v
}

func (o ListTableRoleGrantsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListTableRoleGrantsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Grants) {
		toSerialize["grants"] = o.Grants
	}
	return toSerialize, nil
}

type NullableListTableRoleGrantsResponse struct {
	value *ListTableRoleGrantsResponse
	isSet bool
}

func (v NullableListTableRoleGrantsResponse) Get() *ListTableRoleGrantsResponse {
	return v.value
}

func (v *NullableListTableRoleGrantsResponse) Set(val *ListTableRoleGrantsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListTableRoleGrantsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListTableRoleGrantsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTableRoleGrantsResponse(val *ListTableRoleGrantsResponse) *NullableListTableRoleGrantsResponse {
	return &NullableListTableRoleGrantsResponse{value: val, isSet: true}
}

func (v NullableListTableRoleGrantsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTableRoleGrantsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
