/*
Tabular API

Tabular OpenAPI Definition

API version: 1.54.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tabular

import (
	"encoding/json"
)

// checks if the RoleDatabaseGrantRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoleDatabaseGrantRequest{}

// RoleDatabaseGrantRequest struct for RoleDatabaseGrantRequest
type RoleDatabaseGrantRequest struct {
	RoleId    *string `json:"roleId,omitempty"`
	Privilege *string `json:"privilege,omitempty"`
	WithGrant *bool   `json:"withGrant,omitempty"`
}

// NewRoleDatabaseGrantRequest instantiates a new RoleDatabaseGrantRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleDatabaseGrantRequest() *RoleDatabaseGrantRequest {
	this := RoleDatabaseGrantRequest{}
	return &this
}

// NewRoleDatabaseGrantRequestWithDefaults instantiates a new RoleDatabaseGrantRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleDatabaseGrantRequestWithDefaults() *RoleDatabaseGrantRequest {
	this := RoleDatabaseGrantRequest{}
	return &this
}

// GetRoleId returns the RoleId field value if set, zero value otherwise.
func (o *RoleDatabaseGrantRequest) GetRoleId() string {
	if o == nil || IsNil(o.RoleId) {
		var ret string
		return ret
	}
	return *o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleDatabaseGrantRequest) GetRoleIdOk() (*string, bool) {
	if o == nil || IsNil(o.RoleId) {
		return nil, false
	}
	return o.RoleId, true
}

// HasRoleId returns a boolean if a field has been set.
func (o *RoleDatabaseGrantRequest) HasRoleId() bool {
	if o != nil && !IsNil(o.RoleId) {
		return true
	}

	return false
}

// SetRoleId gets a reference to the given string and assigns it to the RoleId field.
func (o *RoleDatabaseGrantRequest) SetRoleId(v string) {
	o.RoleId = &v
}

// GetPrivilege returns the Privilege field value if set, zero value otherwise.
func (o *RoleDatabaseGrantRequest) GetPrivilege() string {
	if o == nil || IsNil(o.Privilege) {
		var ret string
		return ret
	}
	return *o.Privilege
}

// GetPrivilegeOk returns a tuple with the Privilege field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleDatabaseGrantRequest) GetPrivilegeOk() (*string, bool) {
	if o == nil || IsNil(o.Privilege) {
		return nil, false
	}
	return o.Privilege, true
}

// HasPrivilege returns a boolean if a field has been set.
func (o *RoleDatabaseGrantRequest) HasPrivilege() bool {
	if o != nil && !IsNil(o.Privilege) {
		return true
	}

	return false
}

// SetPrivilege gets a reference to the given string and assigns it to the Privilege field.
func (o *RoleDatabaseGrantRequest) SetPrivilege(v string) {
	o.Privilege = &v
}

// GetWithGrant returns the WithGrant field value if set, zero value otherwise.
func (o *RoleDatabaseGrantRequest) GetWithGrant() bool {
	if o == nil || IsNil(o.WithGrant) {
		var ret bool
		return ret
	}
	return *o.WithGrant
}

// GetWithGrantOk returns a tuple with the WithGrant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleDatabaseGrantRequest) GetWithGrantOk() (*bool, bool) {
	if o == nil || IsNil(o.WithGrant) {
		return nil, false
	}
	return o.WithGrant, true
}

// HasWithGrant returns a boolean if a field has been set.
func (o *RoleDatabaseGrantRequest) HasWithGrant() bool {
	if o != nil && !IsNil(o.WithGrant) {
		return true
	}

	return false
}

// SetWithGrant gets a reference to the given bool and assigns it to the WithGrant field.
func (o *RoleDatabaseGrantRequest) SetWithGrant(v bool) {
	o.WithGrant = &v
}

func (o RoleDatabaseGrantRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoleDatabaseGrantRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RoleId) {
		toSerialize["roleId"] = o.RoleId
	}
	if !IsNil(o.Privilege) {
		toSerialize["privilege"] = o.Privilege
	}
	if !IsNil(o.WithGrant) {
		toSerialize["withGrant"] = o.WithGrant
	}
	return toSerialize, nil
}

type NullableRoleDatabaseGrantRequest struct {
	value *RoleDatabaseGrantRequest
	isSet bool
}

func (v NullableRoleDatabaseGrantRequest) Get() *RoleDatabaseGrantRequest {
	return v.value
}

func (v *NullableRoleDatabaseGrantRequest) Set(val *RoleDatabaseGrantRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleDatabaseGrantRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleDatabaseGrantRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleDatabaseGrantRequest(val *RoleDatabaseGrantRequest) *NullableRoleDatabaseGrantRequest {
	return &NullableRoleDatabaseGrantRequest{value: val, isSet: true}
}

func (v NullableRoleDatabaseGrantRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleDatabaseGrantRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
